<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Read Standard Role</name>
   <tag></tag>
   <elementGuidId>2ba0cf1e-69f0-4080-8bc3-9714c375088f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__BVID__4830']/div[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>87297b95-1590-4269-b91a-8ca0effa4177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-control custom-checkbox</value>
      <webElementGuid>d201c5f3-420f-4a60-b60d-b9cf59166ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Read Standard Role</value>
      <webElementGuid>f5286ea3-61a0-4b55-b984-d248f6034e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__4830&quot;)/div[@class=&quot;custom-control custom-checkbox&quot;]</value>
      <webElementGuid>4c10e33c-3d22-414c-b007-5ab2d9657c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4e17e468-270e-4b5a-b13e-d85c59d07f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-control custom-checkbox</value>
      <webElementGuid>859d8b9a-5c15-4a5c-a03f-62f142b89e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Read Standard Role</value>
      <webElementGuid>2106d131-d3e2-4a23-bd10-6683ba82c0a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__4830&quot;)/div[@class=&quot;custom-control custom-checkbox&quot;]</value>
      <webElementGuid>730b61e5-30a9-458b-915e-bebcf8b66b97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__BVID__4830']/div[7]</value>
      <webElementGuid>4e57605b-1b13-43bc-aa6a-b3a22a62dc5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Write Client'])[1]/following::div[1]</value>
      <webElementGuid>69fb7311-4336-4030-854f-b2020a1398a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read Client'])[1]/following::div[2]</value>
      <webElementGuid>d2b0dd7a-69d4-4853-8df3-278e3d8289ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Write Standard Role'])[1]/preceding::div[1]</value>
      <webElementGuid>6394febe-6a9e-446b-b2c4-82fd2e9cd07b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]</value>
      <webElementGuid>9eb57a0c-a2c7-4a1e-a0bf-0f7e8152247a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Read Standard Role' or . = 'Read Standard Role')]</value>
      <webElementGuid>cc977581-fb82-45ee-a0af-d8aa33bcc284</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
