<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Enter the email address associated with_1b6bcc</name>
   <tag></tag>
   <elementGuidId>2de7a9ad-4af2-4427-b2c8-eae93a95c389</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.description.opacity-6.col</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div[2]/div/div/div/div/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d1a26cc7-3fca-414e-825f-8a79fd1a5339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>description opacity-6 col</value>
      <webElementGuid>ee286480-d1bc-4374-8b07-aa52411bacbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Enter the email address associated with your account, and we'll email you a link to reset your password. </value>
      <webElementGuid>991aa66d-e835-4bcd-a364-eaa23b772032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[2]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row justify-content-center min-vh-100&quot;]/div[@class=&quot;align-self-center col-7&quot;]/div[@class=&quot;mx-auto w-75&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;row mt-2&quot;]/div[@class=&quot;description opacity-6 col&quot;]</value>
      <webElementGuid>5fdd0a24-5faa-410f-b8b0-2ee9874024dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[2]/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>6957bf67-4bb7-4dba-b5ff-84cb0d67ceb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset Password'])[1]/following::div[2]</value>
      <webElementGuid>600173ea-1686-4f28-97cd-e3850bac1986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::div[1]</value>
      <webElementGuid>954c231e-fb32-470a-8c02-e5893a9f3047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter a valid email.'])[1]/preceding::div[1]</value>
      <webElementGuid>27700c4f-e3a6-45d8-a358-41ee44895e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div</value>
      <webElementGuid>4613294b-244b-44ee-aaf0-6f01beae2eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot; Enter the email address associated with your account, and we&quot; , &quot;'&quot; , &quot;ll email you a link to reset your password. &quot;) or . = concat(&quot; Enter the email address associated with your account, and we&quot; , &quot;'&quot; , &quot;ll email you a link to reset your password. &quot;))]</value>
      <webElementGuid>f3486513-604f-4ead-9de0-63b8feb0a7b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
