<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1</name>
   <tag></tag>
   <elementGuidId>6161c818-caec-4db5-8d6a-dbf672eb32cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.el-step__icon-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div/div/div/div[2]/div/div/div/div/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4ed39091-d04c-49fe-a1ab-4a95dbf40e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-step__icon-inner</value>
      <webElementGuid>640c257b-6678-4b15-bab7-089d47391f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a94198d6-6100-43dd-8932-d1d6cb3af38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrapper&quot;]/div[@class=&quot;main-content&quot;]/div[1]/div[@class=&quot;pt-5 px-5&quot;]/div[@class=&quot;bg-white border-bottom&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;py-4&quot;]/div[1]/div[@class=&quot;el-steps el-steps--horizontal&quot;]/div[@class=&quot;el-step is-horizontal is-center&quot;]/div[@class=&quot;el-step__head is-process&quot;]/div[@class=&quot;el-step__icon is-text&quot;]/div[@class=&quot;el-step__icon-inner&quot;]</value>
      <webElementGuid>d76ecc6f-a1a8-40fe-a9f5-041db83a3412</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/div/div[2]/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>2f975f35-ba5f-40aa-a0c2-0701f9b46cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create new Role'])[1]/following::div[10]</value>
      <webElementGuid>740ba415-0eb1-4d13-8f16-1631590665b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Participant'])[2]/following::div[13]</value>
      <webElementGuid>cfed2b78-89ff-440c-861b-c7d19b58313b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role Information'])[1]/preceding::div[1]</value>
      <webElementGuid>fffdae17-0a40-442d-8944-76aee3ead7b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permissions'])[1]/preceding::div[8]</value>
      <webElementGuid>4b31f809-afad-4997-b572-6861a47966c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1']/parent::*</value>
      <webElementGuid>8c6bca47-9914-46ac-b42a-bf0d2fe2c8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>ee2c68ea-16d3-4f16-9964-f77dbb3be065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1' or . = '1')]</value>
      <webElementGuid>b6da2e67-bc2f-4512-955d-85ec3d0de8bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
