<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Roles</name>
   <tag></tag>
   <elementGuidId>96673c88-55f4-43da-a41c-9030db762f5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapse-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#collapse-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>03e97ada-8c95-47d9-9d77-92c895bacb12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>collapse-1</value>
      <webElementGuid>f434cdd3-7b49-4189-bbe1-10e308db8cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-2 collapse show</value>
      <webElementGuid>a50fef22-a228-4905-86b2-0a4ae0db7767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Roles </value>
      <webElementGuid>b5fea7ab-8136-49e0-ae86-5671f3d4686a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse-1&quot;)</value>
      <webElementGuid>e5fb6c06-0500-4566-a15f-26acc603f21d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='collapse-1']</value>
      <webElementGuid>2bd31938-f1fa-4f63-b214-d8123894dc04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidenav-collapse-main']/ul/li[7]/div</value>
      <webElementGuid>58dca336-b5d7-4f2f-89df-c3f040503158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Management'])[1]/following::div[1]</value>
      <webElementGuid>914c1924-9800-45a2-a018-18398144448a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOOLS'])[1]/following::div[1]</value>
      <webElementGuid>743f6fa6-757f-4c80-ae09-bc06d50a91d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created with Fabric.js 1.7.22'])[1]/preceding::div[1]</value>
      <webElementGuid>620ee355-8ac2-4a2c-86ee-e3f8a4ddf98c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/div</value>
      <webElementGuid>f14a379c-c1c5-42cc-9027-7fa2a9659025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'collapse-1' and (text() = ' Roles ' or . = ' Roles ')]</value>
      <webElementGuid>f3e66115-2888-4a50-a771-8b243b6cb2a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
