<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Create new Role</name>
   <tag></tag>
   <elementGuidId>0cded2b4-e020-4d61-ad01-9d0ab3ed1703</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h3[@class=&quot;modal-title&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__BVID__2962___BV_modal_title_</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>b91e268b-5ab0-4b3f-9b23-4b0b089835f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__2962___BV_modal_title_</value>
      <webElementGuid>a5b901fb-3361-4518-ae7e-6b38298ffeb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title</value>
      <webElementGuid>0bdf4baf-58c4-40cd-b9bd-3410f5585a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create new Role</value>
      <webElementGuid>c8109c7e-7f4f-4358-9ccb-b8516106f754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__2962___BV_modal_title_&quot;)</value>
      <webElementGuid>6980c803-4b9a-4466-8a20-af8a3093d418</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h3[@id='__BVID__2962___BV_modal_title_']</value>
      <webElementGuid>13b097aa-f730-401a-aebb-c5c74dcca262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='__BVID__2962___BV_modal_header_']/h3</value>
      <webElementGuid>60577de3-5030-426c-956b-29a72acae8fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', '__BVID__2962', '&quot;', ')')])[1]/following::h3[1]</value>
      <webElementGuid>bda34cff-85e4-4e1b-9fef-56dacda22952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[2]/following::h3[1]</value>
      <webElementGuid>b7c5e2f9-97c2-4768-8eb3-3162583439b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes, Cancel'])[1]/preceding::h3[1]</value>
      <webElementGuid>fd6e6a38-6053-40c6-bc35-1e1b43e841dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No, Continue'])[1]/preceding::h3[1]</value>
      <webElementGuid>0aed5a91-6a42-4806-9401-689c54c8a697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>c2aa23f1-5a7b-4118-8b85-0f9156f9b649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[@id = '__BVID__2962___BV_modal_title_' and (text() = 'Create new Role' or . = 'Create new Role')]</value>
      <webElementGuid>627a041f-ef2c-432b-aa5b-6ffc1fba2a8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
