<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>e961a02c-d936-4208-be44-421c007e7b4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;arrow&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='arrow']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4a16d691-f5a9-4234-beb8-f924ef0910da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/arrow_down.75324a79.svg</value>
      <webElementGuid>84c28677-7e09-4176-bc92-5ba64a444e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>arrow</value>
      <webElementGuid>090377b7-03bc-4b06-88a8-b432e7b46afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0.2732093350725082&quot;)/ul[@class=&quot;navbar-nav align-items-center d-none d-md-flex ml-auto&quot;]/li[@class=&quot;nav-item dropdown cursor-pointer&quot;]/li[@class=&quot;pr-0 dropdown&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[@class=&quot;media-body ml-2 d-none d-lg-block&quot;]/img[1]</value>
      <webElementGuid>503557d9-a654-43b0-aaca-5a97b9edf919</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0.2732093350725082']/ul/li[4]/li/div/div/img</value>
      <webElementGuid>d3cded91-21e9-4d1b-8d6c-80d097a4966f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='arrow']</value>
      <webElementGuid>fb3baea5-5d3b-4eb2-aa9e-6aa24b1f6434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/img</value>
      <webElementGuid>3e27bd05-547b-4c96-82a0-f8e448196eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/img/arrow_down.75324a79.svg' and @alt = 'arrow']</value>
      <webElementGuid>5e66d7f6-7f35-4eda-af4d-e40b4df64665</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
