<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lesser</name>
   <tag></tag>
   <elementGuidId>d0882af9-aa39-452f-8e06-6cf6b98d018f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div/div/div/div/div[3]/nav/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.VuePagination__pagination-item.page-item.VuePagination__pagination-item.VuePagination__pagination-item-prev-page.page-item.disabled.VuePagination__pagination-item-prev-page.disabled</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c8993687-6180-4bb6-b46e-402be575ac58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>VuePagination__pagination-item page-item VuePagination__pagination-item VuePagination__pagination-item-prev-page page-item  disabled VuePagination__pagination-item-prev-page disabled</value>
      <webElementGuid>963bb381-0c94-4dec-a408-5d59574d1400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;</value>
      <webElementGuid>949302bd-fc41-4ace-864f-229fcfcccf35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrapper&quot;]/div[@class=&quot;main-content&quot;]/div[1]/div[@class=&quot;m-5&quot;]/div[@class=&quot;VueTables VueTables--client&quot;]/div[@class=&quot;VuePagination row col-md-12&quot;]/nav[@class=&quot;text-center&quot;]/ul[@class=&quot;VuePagination__pagination pagination VuePagination__pagination&quot;]/li[@class=&quot;VuePagination__pagination-item page-item VuePagination__pagination-item VuePagination__pagination-item-prev-page page-item  disabled VuePagination__pagination-item-prev-page disabled&quot;]</value>
      <webElementGuid>8a815a79-7e09-47d4-9c67-5f56cf5f0c84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/div/div/div[3]/nav/ul/li</value>
      <webElementGuid>9c2095ce-c8cf-4b23-b748-5f2352524d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[10]/following::li[1]</value>
      <webElementGuid>8c1e35fc-3353-445c-a8ef-f755e23d617e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[3]/following::li[1]</value>
      <webElementGuid>e9120b81-783e-47da-95ac-84bfd5aa7907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[1]/preceding::li[3]</value>
      <webElementGuid>c5c9f874-2896-4d04-8bcc-de104114f537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li</value>
      <webElementGuid>1af98729-014f-4027-9bd3-7a00eaa5f500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '&lt;' or . = '&lt;')]</value>
      <webElementGuid>994b81c5-9c8d-43fd-b4f2-2f417cee6b1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
