<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Auth Level</name>
   <tag></tag>
   <elementGuidId>94689ca5-c284-4298-bdb2-2d421dca2a71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div/div/div/div/div[2]/table/thead/tr/th[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e76ecf4b-e8b4-4ac1-8589-e66fe5b05e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>VueTables__heading</value>
      <webElementGuid>a3a8ff04-baf0-4598-82d4-fc5fa0fae9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Auth Level</value>
      <webElementGuid>9f5efeef-4c20-4688-840e-5d0994073347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrapper&quot;]/div[@class=&quot;main-content&quot;]/div[1]/div[@class=&quot;m-5&quot;]/div[@class=&quot;VueTables VueTables--client&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;VueTables__table table app-table&quot;]/thead[1]/tr[1]/th[2]/span[@class=&quot;VueTables__heading&quot;]</value>
      <webElementGuid>3ea2a33d-6bd0-41e4-94ad-7864494f90b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/div/div/div[2]/table/thead/tr/th[2]/span</value>
      <webElementGuid>c2f3f8ea-966d-4f3c-9fa1-1d7e9343d0b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role Type'])[1]/following::span[1]</value>
      <webElementGuid>8b7e805a-4ddb-4ed9-b7ab-a80d37b2baaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Records:'])[1]/following::span[2]</value>
      <webElementGuid>ef8cbc59-f2cf-4c36-ae50-da88209dd055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::span[1]</value>
      <webElementGuid>32653b41-3202-4487-af04-c92f1c7658c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Created'])[1]/preceding::span[2]</value>
      <webElementGuid>322eb11a-cb81-47e6-ac10-b8ce6eb8b802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Auth Level']/parent::*</value>
      <webElementGuid>f8bbb1ab-99db-4ba3-a3c5-8c5bd32ce55a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/span</value>
      <webElementGuid>65a9cfe1-ee8d-481c-995e-0b6aa9cb0788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Auth Level' or . = 'Auth Level')]</value>
      <webElementGuid>58d57f7b-2a2c-4f97-bf94-e78dda6e9bd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
