<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description_textarea</name>
   <tag></tag>
   <elementGuidId>b62477df-2bd8-4971-922d-dd154b9e8dc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textarea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@placeholder='Description and notes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f5ec0f15-1074-4ecc-a4bd-0c595f47d734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>117b03c7-2b92-4e04-beac-a24becb68810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter details here...</value>
      <webElementGuid>2e4f1095-006b-4055-b7b6-66ed7dedf7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>faaee00f-150b-494b-af2e-9cd75e2708d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wrap</name>
      <type>Main</type>
      <value>soft</value>
      <webElementGuid>684370df-f3a1-4d79-b5fb-a5fb5060dea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2186f5c8-c068-4288-ab85-a1efe377e0c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>999</value>
      <webElementGuid>b052a5db-8c07-4469-b913-68009df4498d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textarea&quot;)</value>
      <webElementGuid>e224b50e-98fc-40a0-9db5-76c88622494f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//body/div[@id='app']/div[@class='wrapper']/div[@class='main-content']/div/div[@class='pt-5 px-5']/div[@class='bg-white p-5']/div/div[2]/div[1]</value>
      <webElementGuid>b184826f-8612-4bc1-8a0e-28c9c2e3593b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0.2732093350725082']/ul/li[2]/div/div/div/div/div/textarea</value>
      <webElementGuid>8454de54-5215-481b-8cc7-f3b152d4c3e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>1b27b2ca-b582-4041-bb1d-e2caf4ae525f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'textarea' and @placeholder = 'Enter details here...']</value>
      <webElementGuid>218f1e60-cc9a-4bfa-8c95-63d2f95a1a13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
