<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pasha Madjar</name>
   <tag></tag>
   <elementGuidId>4f91d5df-d453-4114-8538-d98d44c16dab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.media-body.ml-2.d-none.d-lg-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='0.7831255310346346']/ul/li[4]/li/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>71a2c4e6-fd56-4662-9154-549eec03cd20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>media-body ml-2 d-none d-lg-block</value>
      <webElementGuid>37a5226e-aaf0-45df-997f-8888701530e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pasha Madjar </value>
      <webElementGuid>77d2bc05-a222-4e51-95fd-97d1342629a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0.7831255310346346&quot;)/ul[@class=&quot;navbar-nav align-items-center d-none d-md-flex ml-auto&quot;]/li[@class=&quot;nav-item dropdown cursor-pointer&quot;]/li[@class=&quot;pr-0 dropdown&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[@class=&quot;media-body ml-2 d-none d-lg-block&quot;]</value>
      <webElementGuid>b60abb66-30a8-449f-a170-b444f0ccf626</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0.7831255310346346']/ul/li[4]/li/div/div</value>
      <webElementGuid>47d003aa-95cb-4bd9-8ad1-538ab561b7c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::div[43]</value>
      <webElementGuid>301f15d6-c54d-4806-8dca-77c5a0098e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::div[43]</value>
      <webElementGuid>17820d8c-ac1b-453e-aa5e-02f541447c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[1]/preceding::div[1]</value>
      <webElementGuid>0519ce8d-8e6f-4ddb-a279-9564d8e91c36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/li/div/div</value>
      <webElementGuid>4460d885-e1fa-4006-a3b5-3c8ecf469ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Pasha Madjar ' or . = ' Pasha Madjar ')]</value>
      <webElementGuid>21ac2b2f-1097-43db-873a-5794ba824132</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
